(ns skillBoard.atoms)

(def poll-key (atom false))
(def poll-time (atom (System/currentTimeMillis)))
(def clock-pulse (atom false))
(def test? (atom false))
(def change-screen? (atom false))
(def draw-time-accumulator (atom 0))
(def draw-time-start (atom (System/currentTimeMillis)))
(def screen-changed? (atom true))